<<<<<<< HEAD
name: backup and upload

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./backup.sh

      - name: Run backup script
        run: ./backup.sh

      - name: Upload backup zip
        uses: actions/upload-artifact@v3.1.3
        with:
          name: backup-files
          path: backup_*.zip
=======
name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./backup.sh

      - name: Run backup script
        run: ./backup.sh

      - name: Upload backup zip
        uses: actions/upload-artifact@v3.1.3
        with:
          name: backup-files
          path: backup_*.zip
>>>>>>> 3b4ed0d4fda2442c414f471b33460a63343a032e
