name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./deploy.sh

      - name: Run backup script
        run: ./deploy.sh