name: Deploy file

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x deploy.sh

      - name: Run Deploy Script
        run: ./deploy.sh

      - name: List contents of dist
        run: ls -l dist/

      - name: Upload Dist Folder
        uses: actions/upload-artifact@1e953d8c4e7a347cd53ab56f536cf87b0c06292a

        with:
          name: deployed-files
          path: dist/



    
